# -*- coding: utf-8 -*-
"""exercícioPython

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vU28S3kY-zifFS2rrdgVe2ftbXISSQgR
"""

notas = [int(input("informe a nota ")) for x in range (4)]
print("a média de notas é: ", sum(notas)/4)

livro1 = "Harry Potter"

livro2 = "Os segredos da mente milionária"

livro3 = "50 tons de cinza"

livro4 = "O pequeno Príncipe"

print( livro1 )

print(livro4)

livros = ["Harry Potter" , "Os segredos da mente milionária" , "50 tons de cinza" , "O pequeno príncipe"]

print(livros)

livros = [livro1 , livro2 , livro3 , livro4]

print(livros)

